"""Hook settings and guard script generation.

Generates .claude/settings.json with PreToolUse hooks and a guard
script that denies writes to frozen files during experiment runs.
"""

from __future__ import annotations

import json
from pathlib import Path


def generate_hook_settings(frozen_files: list[str]) -> dict:
    """Generate .claude/settings.json structure with frozen file protection.

    Args:
        frozen_files: List of filenames that should be protected from writes.

    Returns:
        Dict suitable for writing as settings.json.
    """
    # Build deny list: each frozen file gets Edit and Write denied
    deny = []
    for f in frozen_files:
        deny.append({"tool": "Edit", "path": f"**/{f}"})
        deny.append({"tool": "Write", "path": f"**/{f}"})

    return {
        "permissions": {
            "allow": [
                "Read",
                "Glob",
                "Grep",
                "Bash(git *)",
                "Bash(python3 *)",
            ],
            "deny": deny,
        },
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Edit|Write",
                    "command": ".claude/hooks/guard-frozen.sh",
                }
            ],
        },
    }


def generate_guard_script(frozen_files: list[str]) -> str:
    """Generate a bash guard script that denies writes to frozen files.

    The script reads JSON from stdin (Claude hook protocol), extracts
    the file_path, and checks if it matches any frozen file. If frozen,
    outputs a deny JSON response. If not frozen, exits 0 with no output
    (which means allow).

    Args:
        frozen_files: List of filenames to protect.

    Returns:
        Bash script content as a string.
    """
    frozen_list = " ".join(frozen_files)

    return f"""#!/bin/bash
# Guard script: deny writes to frozen files
# Generated by mlforge -- do not edit manually

FROZEN_FILES="{frozen_list}"

# Read the hook input JSON from stdin
INPUT=$(cat)

# Extract file_path using python3 (portable fallback)
FILE_PATH=$(echo "$INPUT" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('tool_input', {{}}).get('file_path', d.get('tool_input', {{}}).get('path', '')))" 2>/dev/null)

# Get just the basename for matching
BASENAME=$(basename "$FILE_PATH" 2>/dev/null)

# Check if the file is frozen
for frozen in $FROZEN_FILES; do
    if [ "$BASENAME" = "$frozen" ]; then
        # Deny: output JSON block reason
        cat <<DENY_EOF
{{"decision": "deny", "reason": "File '$frozen' is frozen and must not be modified."}}
DENY_EOF
        exit 0
    fi
done

# Allow: no output, exit 0
exit 0
"""


def write_hook_files(target_dir: Path, frozen_files: list[str]) -> None:
    """Create .claude/settings.json and guard hook script in target directory.

    Args:
        target_dir: Root directory where .claude/ will be created.
        frozen_files: List of filenames to protect.
    """
    claude_dir = target_dir / ".claude"
    hooks_dir = claude_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # Write settings.json
    settings = generate_hook_settings(frozen_files)
    settings_path = claude_dir / "settings.json"
    settings_path.write_text(json.dumps(settings, indent=2) + "\n")

    # Write guard script
    guard_path = hooks_dir / "guard-frozen.sh"
    guard_path.write_text(generate_guard_script(frozen_files))
    guard_path.chmod(0o755)
